databases:
  - name: postgresdb
    plan: free
    databaseName: postgresdb_pzsf
    user: postgresdb_pzsf_user

services:
  - type: web
    plan: free
    name: myrender
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn myrender.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgresdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4